from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

import httpx


@runtime_checkable
class ObserverClientProtocol(Protocol):
    async def report_thought(self, payload: dict[str, Any]) -> None: ...

    async def report_activity(self, payload: dict[str, Any]) -> None: ...

    async def send_heartbeat(self, payload: dict[str, Any]) -> None: ...

    async def notify_birth(self, payload: dict[str, Any]) -> httpx.Response: ...

    async def fetch_system_stats(self) -> dict[str, Any]: ...

    async def fetch_messages_count(self) -> int | None: ...

    async def fetch_blog_post_count(self) -> int | None: ...

    async def fetch_votes(self) -> dict[str, Any]: ...

    async def fetch_messages(self) -> dict[str, Any]: ...

    async def mark_messages_read(self, message_ids: list[int]) -> None: ...

    async def fetch_state(self) -> dict[str, Any]: ...


@runtime_checkable
class ChatServiceProtocol(Protocol):
    async def send(self, model_id: str, messages: list[dict[str, str]]) -> dict[str, Any]: ...

    @staticmethod
    def extract_response(data: dict[str, Any]) -> tuple[str, dict[str, Any]]: ...

    @staticmethod
    def extract_usage(usage: dict[str, Any]) -> tuple[int, int]: ...
